CREATE DATABASE IF NOT EXISTS cattledb;
USE cattledb;

CREATE TABLE IF NOT EXISTS cattle (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    breed VARCHAR(255),
    age INT
);

LOAD DATA INFILE '/var/lib/mysql-files/cattle_data.csv'
INTO TABLE cattle
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
