apiVersion: v1
kind: ConfigMap
metadata:
  name: load-data-script
  namespace: sql-namespace
data:
  load-data.sh: |
    #!/bin/bash
    # Wait for MySQL to be up
    until mysql -h localhost -u root -p"my-secret-pw" -e "SELECT 1" mydatabase > /dev/null 2>&1; do
        echo "Waiting for MySQL server..."
        sleep 1
    done
    
    echo "MySQL server is up. Inserting data."
    
    # Insert data into MySQL
    mysql -h localhost -u root -p"my-secret-pw" mydatabase <<EOF
    LOAD DATA LOCAL INFILE '/var/lib/mysql-files/cattle_data.csv'
    INTO TABLE cattle
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;
    EOF
    
    echo "Data inserted successfully."
