apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sql-namespace
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: script-volume
          configMap:
            name: load-data-script
        - name: data-volume
          configMap:
              name: cattle-data
      initContainers:
        - name: init-db
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
          volumeMounts:
            - name: script-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: csv-data-volume
              mountPath: /var/lib/mysql-files
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "my-secret-pw"
          - name: MYSQL_DATABASE
            value: "mydatabase"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: csv-data-volume
            mountPath: /var/lib/mysql-files



