apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sql-namespace
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my-secret-pw"
        - name: MYSQL_DATABASE
          value: "mydatabase"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql-files
        - name: init-db-script-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: config-volume
        configMap:
          name: cattle-data
          items:
          - key: cattle_data.csv
            path: cattle_data.csv
      - name: data-volume
        emptyDir: {}
      - name: init-db-script-volume
        configMap:
          name: init-db-script
          items:
          - key: init_db.sql
            path: init_db.sql

