apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sql-namespace
spec:
  ...
  template:
    ...
    spec:
      initContainers:
      - name: load-data
        image: mysql:5.7 # Use the same image as your MySQL container
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql-files
        - name: script-volume
          mountPath: /scripts
        command: ["sh", "/scripts/load-data.sh"]
      containers:
      - name: mysql
        image: mysql:5.7
        ...
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql-files
      volumes:
      - name: config-volume
        configMap:
          name: cattle-data
      - name: data-volume
        emptyDir: {}
      - name: script-volume
        configMap:
          name: load-data-script


