apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sql-namespace
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'cp /tmp/config/cattle_data.csv /tmp/data/cattle_data.csv']
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/config
        - name: data-volume
          mountPath: /tmp/data
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my-secret-pw"
        - name: MYSQL_DATABASE
          value: "mydatabase"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql-files
      volumes:
      - name: config-volume
        configMap:
          name: cattle-data
      - name: data-volume
        emptyDir: {}

