apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sql-namespace
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "YOUR_PASSWORD"
      ports:
        - containerPort: 3306
